server:
  port: 8086

spring:
  application:
    name: ms-reportes

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      ms-clientes:
        baseConfig: default
      ms-ordenes:
        baseConfig: default
      ms-facturacion:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s