server:
  port: 8085

spring:
  application:
    name: ms-facturacion

  datasource:
    url: jdbc:mysql://localhost:3306/taller_facturacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      ms-clientes:
        baseConfig: default
      ms-catalogos:
        baseConfig: default
      ms-ordenes:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s