server:
  port: 8087

spring:
  application:
    name: ms-auth

  datasource:
    url: jdbc:mysql://localhost:3306/taller_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "aB3xK9mP2qR7tY5wZ8nL4cV6bN1jH0gF3dS9aQ2eW5rT8yU1iO4pL7kM0nJ6hB"
  expiration-days: 7